#!/bin/sh /etc/rc.common

# Kick a problematic client - a client that has issues with re-authing when needed or otherwise becomes unreachable
  
START=90
STOP=01
USE_PROCD=1
 
start_service() {
	procd_open_instance
	procd_set_param command /bin/sh "/etc/root/kick_problematic_client.sh"
	procd_append_param command daemon
	procd_set_param pidfile /var/run/kick_problematic_client.pid
	procd_set_param stdout 1
	procd_set_param respawn 150 10 10
	procd_close_instance
}
